"""Daily ingest entrypoint.

Run:  python -m src.ingest

Writes:
  data/incidents.json          canonical deduplicated corpus
  data/summary.json            derived reliability metrics
  data/daily/YYYY-MM-DD.json   that day's new + changed incidents
  docs/index.md                human-readable digest

Exits 0 with no writes if nothing changed upstream. That "no-op on no
news" behaviour is deliberate: the commit history should reflect real
upstream activity, not a heartbeat.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import pathlib
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from src import metrics, providers  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
log = logging.getLogger("ingest")


def load_providers() -> list[dict]:
    with open(ROOT / "providers.yaml") as fh:
        return yaml.safe_load(fh)["providers"]


def load_corpus() -> dict[str, dict]:
    path = DATA / "incidents.json"
    if not path.exists():
        return {}
    with open(path) as fh:
        return {f"{i['provider_id']}:{i['incident_id']}": i for i in json.load(fh)}


def write_json(path: pathlib.Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")


def render_digest(summary: dict, new: list[dict], changed: list[dict]) -> str:
    today = dt.date.today().isoformat()
    lines = [
        "# Cloud Incident Atlas",
        "",
        f"Cross-vendor incident data for {summary['providers_tracked']} providers. "
        f"Corpus: **{summary['total_incidents']:,} incidents**. Updated {today}.",
        "",
        "## Last 30 days",
        "",
        f"- Incidents recorded: **{summary['last_30_days']['incident_count']}**",
        f"- Major or worse: **{summary['last_30_days']['major_or_worse']}**",
        "",
        "## Reliability by provider (all time)",
        "",
        "| Provider | Category | Incidents | Median MTTR | p90 MTTR |",
        "| --- | --- | ---: | ---: | ---: |",
    ]

    for stats in summary["by_provider"].values():
        med = f"{stats['mttr_minutes_median']:.0f}m" if stats["mttr_minutes_median"] else "—"
        p90 = f"{stats['mttr_minutes_p90']:.0f}m" if stats["mttr_minutes_p90"] else "—"
        lines.append(
            f"| {stats['provider_name']} | {stats['category']} | "
            f"{stats['incident_count']} | {med} | {p90} |"
        )

    if new:
        lines += ["", f"## New since last run ({len(new)})", ""]
        for inc in new[:25]:
            lines.append(f"- **{inc['provider_name']}** — {inc['title']} (`{inc['severity']}`)")

    if changed:
        lines += ["", f"## Updated since last run ({len(changed)})", ""]
        for inc in changed[:25]:
            lines.append(f"- **{inc['provider_name']}** — {inc['title']} → `{inc['status']}`")

    lines += [
        "",
        "---",
        "",
        "*Generated by the automated ingest pipeline in this repository. "
        "See the README for how the automation works.*",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="fetch and report, write nothing")
    args = ap.parse_args()

    corpus = load_corpus()
    log.info("existing corpus: %d incidents", len(corpus))

    fetched: list[dict] = []
    for cfg in load_providers():
        fetched.extend(i.as_dict() for i in providers.fetch(cfg))

    if not fetched:
        log.error("every provider failed — aborting without writes")
        return 1

    new, changed = [], []
    for inc in fetched:
        key = f"{inc['provider_id']}:{inc['incident_id']}"
        prior = corpus.get(key)
        if prior is None:
            new.append(inc)
            corpus[key] = inc
        elif prior != inc:
            changed.append(inc)
            corpus[key] = inc

    log.info("new=%d changed=%d total=%d", len(new), len(changed), len(corpus))

    if not new and not changed:
        log.info("no upstream changes — nothing to commit")
        return 0

    if args.dry_run:
        log.info("dry run, skipping writes")
        return 0

    records = sorted(corpus.values(), key=lambda i: (i["created_at"] or "", i["provider_id"]))
    summary = metrics.build_summary(records)

    write_json(DATA / "incidents.json", records)
    write_json(DATA / "summary.json", summary)
    write_json(
        DATA / "daily" / f"{dt.date.today().isoformat()}.json",
        {"date": dt.date.today().isoformat(), "new": new, "changed": changed},
    )

    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "index.md").write_text(render_digest(summary, new, changed))

    log.info("wrote corpus, summary, daily delta, digest")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
