"""Daily ingest entrypoint.

Run:  python -m src.ingest

Writes:
  data/incidents.json          canonical deduplicated corpus
  data/summary.json            derived reliability metrics
  data/daily/YYYY-MM-DD.json   that day's new + changed incidents
  docs/index.md                human-readable digest

Exits 0 with no writes if nothing changed upstream. That "no-op on no
news" behaviour is deliberate: the commit history should reflect real
upstream activity, not a heartbeat.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import pathlib
import subprocess
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from src import health, metrics, providers, site

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
log = logging.getLogger("ingest")


def utc_today() -> str:
    """Current date in UTC.

    Must not use date.today(): that reads local time. Runners are UTC and
    this machine is IST (UTC+5:30), so between 00:00 and 05:30 IST the two
    disagree on the date and write to different daily delta files.
    """
    return dt.datetime.now(dt.timezone.utc).date().isoformat()


def load_providers() -> list[dict]:
    with open(ROOT / "providers.yaml") as fh:
        return yaml.safe_load(fh)["providers"]


def load_corpus() -> dict[str, dict]:
    """Load the corpus from per-year shards.

    Sharded rather than one file: a single 12MB blob is rewritten in full on
    every daily run, so git stores a fresh copy per commit and the repo grows
    without bound. Sharding means a run touches only the current year.
    """
    out: dict[str, dict] = {}
    for path in sorted((DATA / "incidents").glob("*.json")):
        with open(path) as fh:
            for i in json.load(fh):
                out[f"{i['provider_id']}:{i['incident_id']}"] = i
    return out


def write_corpus(records: list[dict]) -> None:
    by_year: dict[str, list[dict]] = {}
    for rec in records:
        year = (rec.get("created_at") or "0000")[:4]
        by_year.setdefault(year, []).append(rec)
    for year, recs in by_year.items():
        write_json(DATA / "incidents" / f"{year}.json", recs)


def write_json(path: pathlib.Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")


def render_digest(summary: dict, new: list[dict], changed: list[dict]) -> str:
    today = utc_today()
    lines = [
        "# Cloud Incident Atlas",
        "",
        (
            f"Cross-vendor incident data for {summary['providers_tracked']} providers. "
            f"Corpus: **{summary['total_incidents']:,} incidents**. Updated {today}."
        ),
        "",
        "## Last 30 days",
        "",
        f"- Incidents recorded: **{summary['last_30_days']['incident_count']}**",
        f"- Major or worse: **{summary['last_30_days']['major_or_worse']}**",
        "",
        "## Reliability by provider (all time)",
        "",
        "| Provider | Category | Incidents | Median MTTR | p90 MTTR |",
        "| --- | --- | ---: | ---: | ---: |",
    ]

    for stats in summary["by_provider"].values():
        med = f"{stats['mttr_minutes_median']:.0f}m" if stats["mttr_minutes_median"] else "—"
        p90 = f"{stats['mttr_minutes_p90']:.0f}m" if stats["mttr_minutes_p90"] else "—"
        lines.append(
            f"| {stats['provider_name']} | {stats['category']} | "
            f"{stats['incident_count']} | {med} | {p90} |"
        )

    if new:
        lines += ["", f"## New since last run ({len(new)})", ""]
        for inc in new[:25]:
            lines.append(f"- **{inc['provider_name']}** — {inc['title']} (`{inc['severity']}`)")

    if changed:
        lines += ["", f"## Updated since last run ({len(changed)})", ""]
        for inc in changed[:25]:
            lines.append(f"- **{inc['provider_name']}** — {inc['title']} → `{inc['status']}`")

    lines += [
        "",
        "---",
        "",
        (
            "*Generated by the automated ingest pipeline in this repository. "
            "See the README for how the automation works.*"
        ),
    ]
    return "\n".join(lines) + "\n"


def merge_daily(day: str, new: list[dict], changed: list[dict]) -> dict:
    """Merge into an existing same-day delta rather than overwriting it.

    The pipeline can run more than once a day (scheduled run, manual re-run,
    a backfill). Each run only knows what changed since the previous run, so
    writing its own view wholesale would erase the earlier runs' records for
    that day. The daily file is the per-day audit trail; it must accumulate.

    An incident first seen today stays in `new` even if a later run sees it
    change - it is still new as of today.
    """
    path = DATA / "daily" / f"{day}.json"
    prior = {"new": [], "changed": []}
    if path.exists():
        with open(path) as fh:
            prior = json.load(fh)

    def key(i: dict) -> str:
        return f"{i['provider_id']}:{i['incident_id']}"

    merged_new = {key(i): i for i in prior.get("new", [])}
    for i in new:
        merged_new.setdefault(key(i), i)

    # later state wins for changed, but never shadow something new today
    merged_changed = {key(i): i for i in prior.get("changed", [])}
    for i in changed:
        merged_changed[key(i)] = i
    merged_changed = {k: v for k, v in merged_changed.items() if k not in merged_new}

    return {
        "date": day,
        "runs": prior.get("runs", 0) + 1,
        "new": sorted(merged_new.values(), key=key),
        "changed": sorted(merged_changed.values(), key=key),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="fetch and report, write nothing")
    args = ap.parse_args()

    today = utc_today()
    corpus = load_corpus()
    log.info("existing corpus: %d incidents", len(corpus))

    fetched: list[dict] = []
    counts: dict[str, int] = {}
    for cfg in load_providers():
        records = [i.as_dict() for i in providers.fetch(cfg)]
        counts[cfg["id"]] = len(records)
        fetched.extend(records)

    baseline, alerts = health.update(counts)
    health.write(baseline)
    for alert in alerts:
        log.error("DRIFT %s", alert)
    if alerts:
        (ROOT / "drift.txt").write_text("\n".join(alerts) + "\n")

    if not fetched:
        log.error("every provider failed — aborting without writes")
        return 1

    new, changed = [], []
    for inc in fetched:
        key = f"{inc['provider_id']}:{inc['incident_id']}"
        prior = corpus.get(key)
        if prior is None:
            new.append(inc)
            corpus[key] = inc
        elif prior != inc:
            changed.append(inc)
            corpus[key] = inc

    log.info("new=%d changed=%d total=%d", len(new), len(changed), len(corpus))

    if not new and not changed:
        log.info("no upstream changes — nothing to commit")
        return 0

    if args.dry_run:
        log.info("dry run, skipping writes")
        return 0

    records = sorted(corpus.values(), key=lambda i: (i["created_at"] or "", i["provider_id"]))
    summary = metrics.build_summary(records)

    write_corpus(records)
    write_json(DATA / "summary.json", summary)
    write_json(DATA / "daily" / f"{today}.json", merge_daily(today, new, changed))

    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "index.md").write_text(render_digest(summary, new, changed))

    # Regenerate the rest of the site content too. These pages are also built
    # during the Pages deploy, but committing them keeps the repo copy in step
    # with the published site rather than frozen at whenever they last ran.
    site.main()

    # Regenerate the README charts too. They are committed artefacts read by
    # GitHub directly, so unlike the site they do not get rebuilt on deploy -
    # without this they freeze at whenever they were last run by hand.
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "charts.py")],
        check=False, capture_output=True, text=True,
    )
    if result.returncode != 0:
        # Not fatal - a chart failure must not cost us an ingest - but it must
        # not be silent either, or the charts freeze and nothing ever says so.
        log.error("chart generation failed (rc=%s): %s",
                  result.returncode, (result.stderr or "").strip()[:300])

    log.info("wrote corpus, summary, daily delta, digest")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
